dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t latex .
      - docker images
      - docker tag latex $DOCKER_USERNAME/latex
      - travis_wait docker push $DOCKER_USERNAME/latex